name: Actualizar Dólar

on:
  workflow_dispatch:
  schedule:
    - cron: "2 21 * * *"
    - cron: "0 16 * * *"
    - cron: "30 16 * * *"
    - cron: "45 16 * * *"
    - cron: "10 17 * * *"

jobs:
  dolar_oficial:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run scraping
        env:
           CHROME_PATH: ${{ env.CHROME_PATH }}
        run: node server.js --oficial

      - name: Git operations
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git fetch origin master
          # Aquí ejecutas el scraping, que modifica data.js
          git add -f data.js
          git commit -m "Update dollar rates [skip ci]" || echo "No changes to commit"
          git push -f origin master

  dolar_paralelo:
    needs: dolar_oficial
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
           chrome-version: stable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run scraping
        env:
           CHROME_PATH: ${{ env.CHROME_PATH }}
        run: node server.js --oficial

      - name: Git operations
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git fetch origin master
          # Aquí ejecutas el scraping, que modifica data.js
          git add -f data.js
          git commit -m "Update dollar rates [skip ci]" || echo "No changes to commit"
          git push -f origin master



