name: Actualizar Dólar

on:
  workflow_dispatch:
  schedule:
    - cron: '2 21 * * *'
    - cron: '0 16 * * *'
    - cron: '30 16 * * *'
    - cron: '45 16 * * *'
    - cron: '10 17 * * *'

jobs:
  dolar_oficial:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npx puppeteer browsers install chrome

      - name: Run scraping
        run: node server.js --oficial

      - name: Update repository
        run: |
          # Configurar Git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # Obtener cambios remotos primero
          git fetch origin master
          
          # Guardar cambios locales en data.js
          git add data.js
          
          # Crear commit con los cambios
          git commit -m "Update dollar rates $(date '+%Y-%m-%d %H:%M:%S')"
          
          # Rebase con los cambios remotos
          git rebase origin/master
          
          # Push forzado para asegurar que los cambios se suban
          git push -f origin master

  dolar_paralelo:
    needs: dolar_oficial
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npx puppeteer browsers install chrome

      - name: Run scraping
        run: node server.js --paralelo

      - name: Update repository
        run: |
          # Configurar Git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # Obtener cambios remotos primero
          git fetch origin master
          
          # Guardar cambios locales en data.js
          git add data.js
          
          # Crear commit con los cambios
          git commit -m "Update dollar rates $(date '+%Y-%m-%d %H:%M:%S')"
          
          # Rebase con los cambios remotos
          git rebase origin/master
          
          # Push forzado para asegurar que los cambios se suban
          git push -f origin master