name: Actualizar Dólar

on:
  schedule:
    # Horario para el dólar oficial (5:02 PM Venezuela)
    - cron: '2 21 * * *'
    # Horarios para el dólar paralelo
    - cron: '0 16 * * *'  # 12:00 PM Venezuela
    - cron: '30 16 * * *' # 12:30 PM Venezuela
    - cron: '45 16 * * *' # 12:45 PM Venezuela
    - cron: '10 17 * * *' # 1:10 PM Venezuela
    
    
 

jobs:
  dolar_oficial:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar scraping del dólar oficial
        run: node server.js --oficial

  dolar_paralelo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar scraping del dólar paralelo
        run: node server.js --paralelo