name: Actualizar Dólar

on:
  workflow_dispatch:
  schedule:
    - cron: '2 21 * * *'
    - cron: '0 16 * * *'
    - cron: '30 16 * * *'
    - cron: '45 16 * * *'
    - cron: '10 17 * * *'

jobs:
  dolar_oficial:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run scraping
        run: node server.js --oficial

      - name: Update repository
        run: |
          # Save current date for commit message
          DATE=$(date '+%Y-%m-%d %H:%M:%S')
          
          # Configure Git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # Stage changes and create temporary commit
          git add data.js
          git commit -m "Temporary commit" || echo "No changes to commit"
          
          # Pull latest changes with rebase
          git pull --rebase origin master
          
          # Push changes
          git push origin master

  dolar_paralelo:
    needs: dolar_oficial
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run scraping
        run: node server.js --paralelo

      - name: Update repository
        run: |
          # Save current date for commit message
          DATE=$(date '+%Y-%m-%d %H:%M:%S')
          
          # Configure Git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # Stage changes and create temporary commit
          git add data.js
          git commit -m "Temporary commit" || echo "No changes to commit"
          
          # Pull latest changes with rebase
          git pull --rebase origin master
          
          # Push changes
          git push origin master