name: Actualizar Dólar

on:
  workflow_dispatch: # Habilita la ejecución manual
  schedule:
    # Horario para el dólar oficial (5:02 PM Venezuela)
    - cron: '2 21 * * *'
    # Horarios para el dólar paralelo
    - cron: '0 16 * * *'  # 12:00 PM Venezuela
    - cron: '30 16 * * *' # 12:30 PM Venezuela
    - cron: '45 16 * * *' # 12:45 PM Venezuela
    - cron: '10 17 * * *' # 1:10 PM Venezuela

jobs:
  dolar_oficial:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm' # Habilita la caché de npm para acelerar las instalaciones

      - name: Configurar Puppeteer para omitir la descarga de Chromium
        env:
          PUPPETEER_SKIP_DOWNLOAD: "true"
        run: echo "Configurado PUPPETEER_SKIP_DOWNLOAD=true"

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar scraping del dólar oficial
        run: node server.js --oficial

      - name: Forzar cambios en data.js
        run: echo "// Actualización forzada $(date)" >> data.js

      - name: Confirmar cambios locales antes del pull
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.js
          git commit -m "Confirmar cambios locales en data.js antes del pull" || echo "Sin cambios para confirmar"

      - name: Subir cambios al repositorio
        run: |
          git pull origin master --rebase # Traer los cambios remotos antes de hacer push
          git add data.js
          git commit -m "Actualizar data.js con los últimos datos del dólar" || echo "Sin cambios para confirmar"
          git push

  dolar_paralelo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configurar Puppeteer para omitir la descarga de Chromium
        env:
          PUPPETEER_SKIP_DOWNLOAD: "true"
        run: echo "Configurado PUPPETEER_SKIP_DOWNLOAD=true"

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar scraping del dólar paralelo
        run: node server.js --paralelo

      - name: Forzar cambios en data.js
        run: echo "// Actualización forzada $(date)" >> data.js

      - name: Confirmar cambios locales antes del pull
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.js
          git commit -m "Confirmar cambios locales en data.js antes del pull" || echo "Sin cambios para confirmar"

      - name: Subir cambios al repositorio
        run: |
          git pull origin master --rebase # Traer los cambios remotos antes de hacer push
          git add data.js
          git commit -m "Actualizar data.js con los últimos datos del dólar" || echo "Sin cambios para confirmar"
          git push