name: Actualizar Dólar

on:
  workflow_dispatch:
  schedule:
    - cron: '2 21 * * *'
    - cron: '0 16 * * *'
    - cron: '30 16 * * *'
    - cron: '45 16 * * *'
    - cron: '10 17 * * *'

jobs:
  dolar_oficial:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run scraping
        run: node server.js --oficial

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Update and commit changes
        run: |
          git add data.js
          git commit -m "Update dollar rates" || echo "No changes to commit"
          git pull --rebase origin master
          git push origin master

  dolar_paralelo:
    needs: dolar_oficial
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run scraping
        run: node server.js --paralelo

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Update and commit changes
        run: |
          git add data.js
          git commit -m "Update parallel dollar rates" || echo "No changes to commit"
          git pull --rebase origin master
          git push origin master