name: Actualizar Dólar

on:
  workflow_dispatch:
  schedule:
    - cron: '2 21 * * *'
    - cron: '0 16 * * *'
    - cron: '30 16 * * *'
    - cron: '45 16 * * *'
    - cron: '10 17 * * *'

jobs:
  dolar_oficial:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npx puppeteer browsers install chrome

      - name: Run scraping
        run: node server.js --oficial

      - name: Update repository
        run: |
          # Guardar la fecha actual para el mensaje de commit
          DATE=$(date '+%Y-%m-%d %H:%M:%S')
          
          # Configurar Git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # Agregar cambios y crear un commit temporal (si hay cambios)
          git add data.js
          git commit -m "Temporary commit" || echo "No changes to commit"
          
          # Guardar cambios locales en un stash para evitar conflictos
          git stash --include-untracked
          
          # Pull de los últimos cambios con rebase
          git pull --rebase origin master
          
          # Aplicar de nuevo los cambios guardados en el stash
          git stash pop || echo "No stashed changes to apply"
          
          # Push de los cambios al repositorio
          git push origin master

  dolar_paralelo:
    needs: dolar_oficial
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer Chrome
        run: npx puppeteer browsers install chrome

      - name: Run scraping
        run: node server.js --paralelo

      - name: Update repository
        run: |
          DATE=$(date '+%Y-%m-%d %H:%M:%S')
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add data.js
          git commit -m "Temporary commit" || echo "No changes to commit"
          git stash || echo "Nothing to stash"
          git pull --rebase origin master
          git stash pop || echo "No stash to apply"
          git push origin master