name: Actualizar Dólar

on:
  workflow_dispatch:
  schedule:
    - cron: '2 21 * * *'
    - cron: '0 16 * * *'
    - cron: '30 16 * * *'
    - cron: '45 16 * * *'
    - cron: '10 17 * * *'

jobs:
  dolar_oficial:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Configurar Puppeteer para omitir la descarga de Chromium
        env:
          PUPPETEER_SKIP_DOWNLOAD: "true"
        run: echo "Configurado PUPPETEER_SKIP_DOWNLOAD=true"

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar scraping del dólar oficial
        run: node server.js --oficial

      - name: Forzar cambios en data.js
        run: |
          echo "// Actualización forzada $(date)" >> data.js
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.js
          git commit -m "Actualizar data.js con los últimos datos del dólar"
          git push

  dolar_paralelo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configurar Puppeteer para omitir la descarga de Chromium
        env:
          PUPPETEER_SKIP_DOWNLOAD: "true"
        run: echo "Configurado PUPPETEER_SKIP_DOWNLOAD=true"

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar scraping del dólar paralelo
        run: node server.js --paralelo

      - name: Forzar cambios en data.js
        run: |
          echo "// Actualización forzada $(date)" >> data.js
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.js
          git commit -m "Actualizar data.js con los últimos datos del dólar"
          git push