name: Actualizar Dólar

on:
  workflow_dispatch:
  schedule:
    - cron: '2 21 * * *'
    - cron: '0 16 * * *'
    - cron: '30 16 * * *'
    - cron: '45 16 * * *'
    - cron: '10 17 * * *'

jobs:
  dolar_oficial:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run scraping
        run: node server.js --oficial

      - name: Git Operations
        run: |
          # Stash any local changes
          git stash

          # Configure Git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # Get latest changes
          git pull origin master
          
          # Restore our changes
          git stash pop
          
          # Add and commit
          git add data.js
          git commit -m "Update dollar rates [skip ci]"
          
          # Push changes
          git push origin master

  dolar_paralelo:
    if: ${{ success() }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run scraping
        run: node server.js --paralelo

      - name: Update repository
        run: |
          # Configure Git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # Pull latest changes
          git pull origin master
          
          # Add and commit changes
          git add data.js
          git commit -m "Update parallel dollar rates" || echo "No changes to commit"
          
          # Push changes
          git push origin master